package tech.wenisch.contextcrate.mcp;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;
import tech.wenisch.contextcrate.answer.AnswerService;
import tech.wenisch.contextcrate.domain.Crate;

/**
 * Builds the advertised tool list for one request.
 *
 * <p>Descriptions are assembled per call rather than declared statically: whether a model retrieves
 * at the right moment depends almost entirely on what the description says, so the crate's own name
 * and description are written into it. The catalogue also states plainly that retrieval is ranked by
 * relevance and is not exhaustive — otherwise a model treats eight hits as the whole corpus.
 */
@Component
public class McpToolCatalog {
  private final AnswerService answers;

  public McpToolCatalog(AnswerService answers) {
    this.answers = answers;
  }

  /**
   * @param crate the bound crate, or null on the global endpoint where it is chosen per call
   */
  public List<Map<String, Object>> tools(Crate crate) {
    boolean global = crate == null;
    List<Map<String, Object>> tools = new ArrayList<>();
    tools.add(searchTool(crate, global));
    if (global || answers.available(crate.getId())) tools.add(askTool(crate, global));
    tools.add(fetchTool(crate, global));
    tools.add(listDocumentsTool(crate, global));
    tools.add(listSourcesTool(crate, global));
    if (global) tools.add(listCratesTool());
    return tools;
  }

  /** One-paragraph orientation returned from {@code initialize}. */
  public String instructions(Crate crate) {
    String subject = crate == null
        ? "the knowledge bases (crates) this credential can reach"
        : "the \"" + crate.getName() + "\" knowledge base";
    return "ContextCrate exposes "
        + subject
        + " for retrieval. Use search_crate for questions about the content; it returns verbatim "
        + "passages ranked by relevance, not an exhaustive list, so treat its results as evidence "
        + "rather than as the complete contents. Use list_documents when asked what the knowledge "
        + "base contains — it is paginated and reports the true total. Use list_sources when asked "
        + "where the content comes from. Cite passages by their [n] markers.";
  }

  private Map<String, Object> searchTool(Crate crate, boolean global) {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("query", property("string", "What to look for. Natural language or keywords."));
    properties.put("limit", property("integer",
        "How many passages to return. Default " + McpTools.SEARCH_DEFAULT_LIMIT
            + ", maximum " + McpTools.SEARCH_MAX_LIMIT + "."));
    properties.put("mode", property("string",
        "Retrieval mode: lexical, semantic, or hybrid. Defaults to the crate's configured mode."));
    addCrate(properties, global);
    return tool(
        "search_crate",
        "Search " + describe(crate, global)
            + " and return the matching passages in full, with title, source URI and score. "
            + "Results are ranked by relevance and are NOT exhaustive — to find out what the "
            + "knowledge base contains, use list_documents instead.",
        properties,
        List.of("query"));
  }

  private Map<String, Object> askTool(Crate crate, boolean global) {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("question", property("string", "The question to answer. At most 8000 characters."));
    properties.put("maxSources", property("integer",
        "Upper bound on retrieved sources. Capped by the crate's configured source limit."));
    addCrate(properties, global);
    return tool(
        "ask_crate",
        "Ask " + describe(crate, global)
            + " a question and get an answer generated by ContextCrate's own retrieval-augmented "
            + "pipeline, grounded in the crate and returned with numbered citations. Prefer "
            + "search_crate when you want the raw passages to reason over yourself.",
        properties,
        List.of("question"));
  }

  private Map<String, Object> fetchTool(Crate crate, boolean global) {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("documentId", property("string",
        "The document UUID, as returned by search_crate or list_documents."));
    properties.put("maxCharacters", property("integer",
        "How much of the body to return. Default " + McpTools.DOCUMENT_DEFAULT_CHARACTERS
            + ", maximum " + McpTools.DOCUMENT_MAX_CHARACTERS + "."));
    properties.put("offset", property("integer", "Where to start in the body, for reading on."));
    addCrate(properties, global);
    return tool(
        "fetch_document",
        "Retrieve the full text of one document from " + describe(crate, global)
            + ". Use after search_crate when a passage needs its surrounding context.",
        properties,
        List.of("documentId"));
  }

  private Map<String, Object> listDocumentsTool(Crate crate, boolean global) {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("query", property("string", "Optional filter on document title or source URI."));
    properties.put("limit", property("integer",
        "How many to return. Default " + McpTools.LIST_DEFAULT_LIMIT
            + ", maximum " + McpTools.LIST_MAX_LIMIT + "."));
    properties.put("offset", property("integer", "Where to start, for paging through everything."));
    addCrate(properties, global);
    return tool(
        "list_documents",
        "List the documents in " + describe(crate, global)
            + " with their titles, source URIs and chunk counts, and report the total number held. "
            + "This is the reliable way to answer what the knowledge base contains or how large it "
            + "is; unlike search_crate it is complete and can be paged through.",
        properties,
        List.of());
  }

  private Map<String, Object> listSourcesTool(Crate crate, boolean global) {
    Map<String, Object> properties = new LinkedHashMap<>();
    addCrate(properties, global);
    return tool(
        "list_sources",
        "List the configured sources that feed " + describe(crate, global)
            + " — the websites and Git repositories it was ingested from, with their connector type "
            + "and whether they are enabled. Use for questions about provenance.",
        properties,
        List.of());
  }

  private Map<String, Object> listCratesTool() {
    return tool(
        "list_crates",
        "List the knowledge bases (crates) this credential can reach, with their names and "
            + "descriptions. Call first when you need to decide which crate a question belongs to.",
        new LinkedHashMap<>(),
        List.of());
  }

  /** The {@code crate} argument exists only on the global endpoint; elsewhere it is already fixed. */
  private static void addCrate(Map<String, Object> properties, boolean global) {
    if (global)
      properties.put("crate", property("string",
          "Which crate to use: its UUID or its exact name. Call list_crates if unsure."));
  }

  private static String describe(Crate crate, boolean global) {
    if (global) return "a knowledge base";
    String described = "the \"" + crate.getName() + "\" knowledge base";
    return crate.getDescription() == null || crate.getDescription().isBlank()
        ? described
        : described + " (contents: " + crate.getDescription() + ")";
  }

  private static Map<String, Object> property(String type, String description) {
    return Map.of("type", type, "description", description);
  }

  private static Map<String, Object> tool(
      String name, String description, Map<String, Object> properties, List<String> required) {
    Map<String, Object> schema = new LinkedHashMap<>();
    schema.put("type", "object");
    schema.put("properties", properties);
    if (!required.isEmpty()) schema.put("required", required);
    if (properties.isEmpty()) schema.put("additionalProperties", false);
    Map<String, Object> tool = new LinkedHashMap<>();
    tool.put("name", name);
    tool.put("description", description);
    tool.put("inputSchema", schema);
    return tool;
  }
}
