package tech.wenisch.contextcrate.mcp;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Component;

/**
 * The advertised tool list.
 *
 * <p>The Model Context Protocol server keeps one tool list for the whole server rather than one per
 * request, so the descriptions here cannot name the crate they will run against. What they must
 * still do is steer the model to the right tool: that {@code search_crate} is ranked by relevance
 * and is <em>not</em> exhaustive, and that {@code list_documents} is the one that can answer what a
 * knowledge base actually contains.
 *
 * <p>The {@code crate} argument is offered on every tool. On the crate-scoped endpoint the path wins
 * regardless, because {@link McpCrateResolver#resolve} prefers the path over the argument.
 */
@Component
public class McpToolCatalog {
  /** Tool definitions as plain maps; {@link McpToolAdapter} turns them into protocol objects. */
  public List<Map<String, Object>> tools() {
    List<Map<String, Object>> tools = new ArrayList<>();
    tools.add(searchTool());
    tools.add(askTool());
    tools.add(fetchTool());
    tools.add(listDocumentsTool());
    tools.add(listSourcesTool());
    tools.add(listCratesTool());
    return tools;
  }

  /** One-paragraph orientation returned from {@code initialize}. */
  public String instructions() {
    return "ContextCrate exposes knowledge bases (crates) for retrieval. Use search_crate for "
        + "questions about the content; it returns verbatim passages ranked by relevance, not an "
        + "exhaustive list, so treat its results as evidence rather than as the complete contents. "
        + "Use list_documents when asked what a knowledge base contains — it is paginated and "
        + "reports the true total. Use list_sources when asked where the content comes from. When "
        + "this endpoint is bound to a single crate the crate argument is ignored; otherwise call "
        + "list_crates first to choose one. Cite passages by their [n] markers.";
  }

  private Map<String, Object> searchTool() {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("query", property("string", "What to look for. Natural language or keywords."));
    properties.put("limit", property("integer",
        "How many passages to return. Default " + McpTools.SEARCH_DEFAULT_LIMIT
            + ", maximum " + McpTools.SEARCH_MAX_LIMIT + "."));
    properties.put("mode", property("string",
        "Retrieval mode: lexical, semantic, or hybrid. Defaults to the crate's configured mode."));
    addCrate(properties);
    return tool(
        "search_crate",
        "Search a ContextCrate knowledge base and return the matching passages in full, with title, "
            + "source URI and score. Results are ranked by relevance and are NOT exhaustive — to "
            + "find out what the knowledge base contains, use list_documents instead.",
        properties,
        List.of("query"));
  }

  private Map<String, Object> askTool() {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("question", property("string", "The question to answer. At most 8000 characters."));
    properties.put("maxSources", property("integer",
        "Upper bound on retrieved sources. Capped by the crate's configured source limit."));
    addCrate(properties);
    return tool(
        "ask_crate",
        "Ask a ContextCrate knowledge base a question and get an answer generated by its own "
            + "retrieval-augmented pipeline, grounded in the crate and returned with numbered "
            + "citations. Prefer search_crate when you want the raw passages to reason over "
            + "yourself. Reports an error when answer generation is not configured for the crate.",
        properties,
        List.of("question"));
  }

  private Map<String, Object> fetchTool() {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("documentId", property("string",
        "The document UUID, as returned by search_crate or list_documents."));
    properties.put("maxCharacters", property("integer",
        "How much of the body to return. Default " + McpTools.DOCUMENT_DEFAULT_CHARACTERS
            + ", maximum " + McpTools.DOCUMENT_MAX_CHARACTERS + "."));
    properties.put("offset", property("integer", "Where to start in the body, for reading on."));
    addCrate(properties);
    return tool(
        "fetch_document",
        "Retrieve the full text of one document from a ContextCrate knowledge base. Use after "
            + "search_crate when a passage needs its surrounding context.",
        properties,
        List.of("documentId"));
  }

  private Map<String, Object> listDocumentsTool() {
    Map<String, Object> properties = new LinkedHashMap<>();
    properties.put("query", property("string", "Optional filter on document title or source URI."));
    properties.put("limit", property("integer",
        "How many to return. Default " + McpTools.LIST_DEFAULT_LIMIT
            + ", maximum " + McpTools.LIST_MAX_LIMIT + "."));
    properties.put("offset", property("integer", "Where to start, for paging through everything."));
    addCrate(properties);
    return tool(
        "list_documents",
        "List the documents in a ContextCrate knowledge base with their titles, source URIs and "
            + "chunk counts, and report the total number held. This is the reliable way to answer "
            + "what a knowledge base contains or how large it is; unlike search_crate it is "
            + "complete and can be paged through.",
        properties,
        List.of());
  }

  private Map<String, Object> listSourcesTool() {
    Map<String, Object> properties = new LinkedHashMap<>();
    addCrate(properties);
    return tool(
        "list_sources",
        "List the configured sources that feed a ContextCrate knowledge base — the websites and Git "
            + "repositories it was ingested from, with their connector type and whether they are "
            + "enabled. Use for questions about provenance.",
        properties,
        List.of());
  }

  private Map<String, Object> listCratesTool() {
    return tool(
        "list_crates",
        "List the knowledge bases (crates) this credential can reach, with their names and "
            + "descriptions. Call first when you need to decide which crate a question belongs to.",
        new LinkedHashMap<>(),
        List.of());
  }

  private static void addCrate(Map<String, Object> properties) {
    properties.put("crate", property("string",
        "Which crate to use: its UUID or its exact name. Ignored when the endpoint is already bound "
            + "to one crate. Call list_crates if unsure."));
  }

  private static Map<String, Object> property(String type, String description) {
    return Map.of("type", type, "description", description);
  }

  private static Map<String, Object> tool(
      String name, String description, Map<String, Object> properties, List<String> required) {
    Map<String, Object> schema = new LinkedHashMap<>();
    schema.put("type", "object");
    schema.put("properties", properties);
    if (!required.isEmpty()) schema.put("required", required);
    if (properties.isEmpty()) schema.put("additionalProperties", false);
    Map<String, Object> tool = new LinkedHashMap<>();
    tool.put("name", name);
    tool.put("description", description);
    tool.put("inputSchema", schema);
    return tool;
  }
}
