package tech.wenisch.contextcrate.domain;
import jakarta.persistence.*;
@Entity @Table(name="crate_provider_settings")
public class ProviderSettings {
  @Id @Column(name="crate_id") private java.util.UUID crateId; private Boolean embeddingsEnabled; private String embeddingsProvider; private String embeddingLocalModelId; private String embeddingLocalRevision; @Column(length=2000) private String embeddingLocalDownloadUrl; private String embeddingLocalCachePath; private String embeddingLocalModelPath; @Column(length=2000) private String embeddingOpenaiBaseUrl; private String embeddingOpenaiModel; @Column(length=2000) private String embeddingOpenaiApiKey; private Integer embeddingOpenaiDimensions; private Boolean answeringEnabled; @Column(length=2000) private String answeringBaseUrl; private String answeringModel; @Column(length=2000) private String answeringApiKey;
  protected ProviderSettings(){} public ProviderSettings(int ignored){this(crateIds());} public ProviderSettings(java.util.UUID crateId){this.crateId=crateId;}
  private static java.util.UUID crateIds(){return CrateIds.LEGACY;}
  public java.util.UUID getCrateId(){return crateId;}
  public Boolean getEmbeddingsEnabled(){return embeddingsEnabled;} public String getEmbeddingsProvider(){return embeddingsProvider;} public String getEmbeddingLocalModelId(){return embeddingLocalModelId;} public String getEmbeddingLocalRevision(){return embeddingLocalRevision;} public String getEmbeddingLocalDownloadUrl(){return embeddingLocalDownloadUrl;} public String getEmbeddingLocalCachePath(){return embeddingLocalCachePath;} public String getEmbeddingLocalModelPath(){return embeddingLocalModelPath;} public String getEmbeddingOpenaiBaseUrl(){return embeddingOpenaiBaseUrl;} public String getEmbeddingOpenaiModel(){return embeddingOpenaiModel;} public String getEmbeddingOpenaiApiKey(){return embeddingOpenaiApiKey;} public Integer getEmbeddingOpenaiDimensions(){return embeddingOpenaiDimensions;} public Boolean getAnsweringEnabled(){return answeringEnabled;} public String getAnsweringBaseUrl(){return answeringBaseUrl;} public String getAnsweringModel(){return answeringModel;} public String getAnsweringApiKey(){return answeringApiKey;}
  public void update(Boolean ee,String ep,String mid,String rev,String url,String cache,String path,String ebase,String emodel,String ekey,Integer dims,Boolean ae,String abase,String amodel,String akey){embeddingsEnabled=ee;embeddingsProvider=ep;embeddingLocalModelId=mid;embeddingLocalRevision=rev;embeddingLocalDownloadUrl=url;embeddingLocalCachePath=cache;embeddingLocalModelPath=path;embeddingOpenaiBaseUrl=ebase;embeddingOpenaiModel=emodel;if(ekey!=null&&!ekey.isBlank())embeddingOpenaiApiKey=ekey;embeddingOpenaiDimensions=dims;answeringEnabled=ae;answeringBaseUrl=abase;answeringModel=amodel;if(akey!=null&&!akey.isBlank())answeringApiKey=akey;}
}
