package tech.wenisch.contextcrate.answer;

import java.util.Set;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tech.wenisch.contextcrate.config.ContextCrateProperties;
import tech.wenisch.contextcrate.domain.RagSettings;
import tech.wenisch.contextcrate.repository.RagSettingsRepository;

@Service
public class RagSettingsService {
  private final RagSettingsRepository settings; private final ContextCrateProperties.Answering config;private final tech.wenisch.contextcrate.config.RuntimeProviderSettings providers;
  public RagSettingsService(RagSettingsRepository settings, ContextCrateProperties properties){this(settings,properties,null);}
  @org.springframework.beans.factory.annotation.Autowired public RagSettingsService(RagSettingsRepository settings,ContextCrateProperties properties,tech.wenisch.contextcrate.config.RuntimeProviderSettings providers){this.settings=settings;this.config=properties.answering();this.providers=providers;}
  @Transactional public RagSettings current(){return current(tech.wenisch.contextcrate.config.CrateContext.current());}
  @Transactional public RagSettings current(java.util.UUID crateId){return settings.findById(crateId).orElseGet(()->settings.save(new RagSettings(crateId,false,true,true,true,true,true,"revise-once",config.retrievalMode(),"standard","fail-indexing",config.sourceLimit())));}
  @Transactional public RagSettings update(boolean strict,boolean history,boolean inline,boolean structured,boolean grading,boolean verification,String verificationAction,String mode,int limit){return update(tech.wenisch.contextcrate.config.CrateContext.current(),strict,history,inline,structured,grading,verification,verificationAction,mode,limit);}
  @Transactional public RagSettings update(java.util.UUID crateId,boolean strict,boolean history,boolean inline,boolean structured,boolean grading,boolean verification,String verificationAction,String mode,int limit){var value=current(crateId);return update(crateId,strict,history,inline,structured,grading,verification,verificationAction,mode,value.getRetrievalStrategy(),value.getPropositionFailurePolicy(),limit);}
  @Transactional public RagSettings update(java.util.UUID crateId,boolean strict,boolean history,boolean inline,boolean structured,boolean grading,boolean verification,String verificationAction,String mode,String strategy,String failurePolicy,int limit){if(!Set.of("lexical","semantic","hybrid").contains(mode))throw new IllegalArgumentException("retrieval mode must be lexical, semantic, or hybrid");if(!Set.of("standard","proposition").contains(strategy))throw new IllegalArgumentException("retrieval strategy must be standard or proposition");if(!Set.of("fail-indexing","skip-chunk","embed-source-chunk").contains(failurePolicy))throw new IllegalArgumentException("invalid proposition failure policy");if(!Set.of("revise-once","block-answer","return-warning").contains(verificationAction))throw new IllegalArgumentException("answer verification action must be revise-once, block-answer, or return-warning");if(limit<1||limit>config.sourceLimit())throw new IllegalArgumentException("source limit must be between 1 and "+config.sourceLimit());if("proposition".equals(strategy))validateProviders(crateId);var value=current(crateId);value.update(strict,history,inline,structured,grading,verification,verificationAction,mode,strategy,failurePolicy,limit);return settings.save(value);}
  public void validateProviders(java.util.UUID crateId){if(providers==null)return;var embedding=providers.effectiveEmbedding(crateId);var answer=providers.effectiveAnswer(crateId);boolean embeddingConfigured=embedding.enabled()&&("local".equals(embedding.provider())||embedding.openaiBaseUrl()!=null&&!embedding.openaiBaseUrl().isBlank()&&embedding.openaiModel()!=null&&!embedding.openaiModel().isBlank());if(!embeddingConfigured)throw new IllegalArgumentException("Proposition retrieval requires configured embeddings");if(!answer.enabled()||answer.baseUrl()==null||answer.baseUrl().isBlank()||answer.model()==null||answer.model().isBlank())throw new IllegalArgumentException("Proposition retrieval requires an enabled and configured answer model");}
}
