FROM mcr.microsoft.com/playwright/java:v1.62.0-noble
WORKDIR /app
ARG BUILD_VERSION=dev
ARG BUILD_REVISION=unknown
LABEL org.opencontainers.image.title="ContextCrate Browser Worker" org.opencontainers.image.licenses="AGPL-3.0" org.opencontainers.image.version="${BUILD_VERSION}" org.opencontainers.image.revision="${BUILD_REVISION}"
RUN useradd --system --uid 65532 --create-home contextcrate
COPY target/contextcrate-*.jar /app/app.jar
RUN chown -R contextcrate:contextcrate /app
USER 65532:65532
ENV CONTEXTCRATE_ROLE=crawler-browser
ENTRYPOINT ["java","-jar","/app/app.jar"]
