package tech.wenisch.contextcrate.config;

import java.nio.file.Path;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tech.wenisch.contextcrate.domain.ProviderSettings;
import tech.wenisch.contextcrate.repository.ProviderSettingsRepository;

/** Database overrides take precedence over environment-bound configuration. */
@Service
public class RuntimeProviderSettings {
  private final ProviderSettingsRepository repository; private final ContextCrateProperties properties;
  public RuntimeProviderSettings(ProviderSettingsRepository repository,ContextCrateProperties properties){this.repository=repository;this.properties=properties;}
  @Transactional(readOnly = true) public ProviderSettings current(){return current(CrateContext.current());}
  @Transactional(readOnly = true) public ProviderSettings current(java.util.UUID crateId){return repository.findById(crateId).orElseThrow(()->new IllegalStateException("Provider settings are not initialized for crate "+crateId));}
  @Transactional public void update(ProviderForm f){update(CrateContext.current(),f);}
  @Transactional public void update(java.util.UUID crateId,ProviderForm f){if(!"local".equals(f.embeddingProvider())&& !"openai-compatible".equals(f.embeddingProvider()))throw new IllegalArgumentException("embedding provider must be local or openai-compatible");if(!"local".equals(f.rerankingProvider())&& !"cohere-compatible".equals(f.rerankingProvider()))throw new IllegalArgumentException("reranking provider must be local or cohere-compatible");if(f.embeddingDimensions()<1)throw new IllegalArgumentException("embedding dimensions must be positive");if(f.embeddingMaxInputCharacters()<256)throw new IllegalArgumentException("maximum embedding input characters must be at least 256");if(f.rerankingCandidateLimit()<1||f.rerankingCandidateLimit()>100)throw new IllegalArgumentException("reranking candidate limit must be between 1 and 100");if(f.rerankingMaxInputCharacters()<256)throw new IllegalArgumentException("maximum reranking input characters must be at least 256");if(f.rerankingTimeoutSeconds()<5)throw new IllegalArgumentException("reranking timeout must be at least 5 seconds");var s=current(crateId);boolean changed=!java.util.Objects.equals(s.getEmbeddingOpenaiBaseUrl(),blank(f.embeddingBaseUrl()))||!java.util.Objects.equals(s.getEmbeddingOpenaiModel(),blank(f.embeddingRemoteModel()));s.update(f.embeddingsEnabled(),f.embeddingProvider(),blank(f.embeddingModelId()),blank(f.embeddingRevision()),blank(f.embeddingDownloadUrl()),blank(f.embeddingCachePath()),blank(f.embeddingModelPath()),blank(f.embeddingBaseUrl()),blank(f.embeddingRemoteModel()),f.embeddingApiKey(),f.embeddingDimensions(),f.embeddingMaxInputCharacters(),f.rerankingEnabled(),f.rerankingProvider(),f.rerankingCandidateLimit(),blank(f.rerankingModelId()),blank(f.rerankingRevision()),blank(f.rerankingDownloadUrl()),blank(f.rerankingCachePath()),blank(f.rerankingModelPath()),blank(f.rerankingBaseUrl()),blank(f.rerankingRemoteModel()),f.rerankingApiKey(),f.rerankingMaxInputCharacters(),f.rerankingTimeoutSeconds(),f.answeringEnabled(),blank(f.answeringBaseUrl()),blank(f.answeringModel()),f.answeringApiKey());s.setEmbeddingOpenaiAutomaticLimitRecovery(f.embeddingAutomaticLimitRecovery());if(changed)s.clearLearnedEmbeddingInputLimit();}
  public Embedding effectiveEmbedding(){var s=current();var e=properties.embeddings();var l=e.local();var o=e.openaiCompatible();String base=choose(s.getEmbeddingOpenaiBaseUrl(),o.baseUrl()),model=choose(s.getEmbeddingOpenaiModel(),o.model());int configured=s.getEmbeddingOpenaiMaxInputCharacters()==null?o.maxInputCharacters():s.getEmbeddingOpenaiMaxInputCharacters();boolean recovery=s.getEmbeddingOpenaiAutomaticLimitRecovery()==null?o.automaticLimitRecovery():s.getEmbeddingOpenaiAutomaticLimitRecovery();Integer learned=java.util.Objects.equals(base,s.getEmbeddingOpenaiLearnedLimitBaseUrl())&&java.util.Objects.equals(model,s.getEmbeddingOpenaiLearnedLimitModel())?s.getEmbeddingOpenaiLearnedMaxInputCharacters():null;return new Embedding(s.getEmbeddingsEnabled()==null?e.enabled():s.getEmbeddingsEnabled(),choose(s.getEmbeddingsProvider(),e.provider()),choose(s.getEmbeddingLocalModelId(),l.modelId()),choose(s.getEmbeddingLocalRevision(),l.revision()),choose(s.getEmbeddingLocalDownloadUrl(),l.downloadUrl()),path(s.getEmbeddingLocalCachePath(),l.cachePath()),pathNullable(s.getEmbeddingLocalModelPath(),l.modelPath()),base,model,choose(s.getEmbeddingOpenaiApiKey(),o.apiKey()),s.getEmbeddingOpenaiDimensions()==null?o.dimensions():s.getEmbeddingOpenaiDimensions(),configured,recovery,learned==null?configured:Math.min(configured,learned));}
  public Embedding effectiveEmbedding(java.util.UUID crateId){try(var ignored=CrateContext.use(crateId)){return effectiveEmbedding();}}
  public Reranking effectiveReranking(){var s=current();var r=properties.reranking();var l=r.local();var c=r.cohereCompatible();return new Reranking(s.getRerankingEnabled()==null?r.enabled():s.getRerankingEnabled(),choose(s.getRerankingProvider(),r.provider()),s.getRerankingCandidateLimit()==null?r.candidateLimit():s.getRerankingCandidateLimit(),choose(s.getRerankingLocalModelId(),l.modelId()),choose(s.getRerankingLocalRevision(),l.revision()),choose(s.getRerankingLocalDownloadUrl(),l.downloadUrl()),path(s.getRerankingLocalCachePath(),l.cachePath()),pathNullable(s.getRerankingLocalModelPath(),l.modelPath()),l.downloadTimeoutSeconds(),choose(s.getRerankingCohereBaseUrl(),c.baseUrl()),choose(s.getRerankingCohereModel(),c.model()),choose(s.getRerankingCohereApiKey(),c.apiKey()),s.getRerankingCohereMaxInputCharacters()==null?c.maxInputCharacters():s.getRerankingCohereMaxInputCharacters(),s.getRerankingCohereTimeoutSeconds()==null?c.timeoutSeconds():s.getRerankingCohereTimeoutSeconds());}
  public Reranking effectiveReranking(java.util.UUID crateId){try(var ignored=CrateContext.use(crateId)){return effectiveReranking();}}
  public Answering effectiveAnswer(){var s=current();var a=properties.answering();var o=a.openaiCompatible();return new Answering(s.getAnsweringEnabled()==null?a.enabled():s.getAnsweringEnabled(),choose(s.getAnsweringBaseUrl(),o.baseUrl()),choose(s.getAnsweringModel(),o.model()),choose(s.getAnsweringApiKey(),o.apiKey()),o.headers(),o.timeoutSeconds(),a.temperature(),a.maxOutputTokens());}
  public Answering effectiveAnswer(java.util.UUID crateId){try(var ignored=CrateContext.use(crateId)){return effectiveAnswer();}}
  private static String choose(String value,String fallback){return value==null||value.isBlank()?fallback:value;}private static Path path(String value,Path fallback){return value==null||value.isBlank()?fallback:Path.of(value);}private static Path pathNullable(String value,Path fallback){return value==null||value.isBlank()?fallback:Path.of(value);}private static String blank(String value){return value==null||value.isBlank()?null:value.trim();}
  @Transactional public void learnEmbeddingInputLimit(java.util.UUID crateId,int maximum,String baseUrl,String model){var s=current(crateId);s.learnEmbeddingInputLimit(maximum,baseUrl,model);}
  public record Embedding(boolean enabled,String provider,String localModelId,String localRevision,String localDownloadUrl,Path localCachePath,Path localModelPath,String openaiBaseUrl,String openaiModel,String openaiApiKey,int openaiDimensions,int openaiMaxInputCharacters,boolean automaticLimitRecovery,int effectiveOpenaiMaxInputCharacters){public Embedding(boolean enabled,String provider,String localModelId,String localRevision,String localDownloadUrl,Path localCachePath,Path localModelPath,String openaiBaseUrl,String openaiModel,String openaiApiKey,int openaiDimensions,int openaiMaxInputCharacters){this(enabled,provider,localModelId,localRevision,localDownloadUrl,localCachePath,localModelPath,openaiBaseUrl,openaiModel,openaiApiKey,openaiDimensions,openaiMaxInputCharacters,true,openaiMaxInputCharacters);}}
  public record Reranking(boolean enabled,String provider,int candidateLimit,String localModelId,String localRevision,String localDownloadUrl,Path localCachePath,Path localModelPath,int localDownloadTimeoutSeconds,String cohereBaseUrl,String cohereModel,String cohereApiKey,int cohereMaxInputCharacters,int cohereTimeoutSeconds){}
  public record Answering(boolean enabled,String baseUrl,String model,String apiKey,String headers,int timeoutSeconds,double temperature,int maxOutputTokens){}
  public record ProviderForm(boolean embeddingsEnabled,String embeddingProvider,String embeddingModelId,String embeddingRevision,String embeddingDownloadUrl,String embeddingCachePath,String embeddingModelPath,String embeddingBaseUrl,String embeddingRemoteModel,String embeddingApiKey,int embeddingDimensions,int embeddingMaxInputCharacters,boolean embeddingAutomaticLimitRecovery,boolean rerankingEnabled,String rerankingProvider,int rerankingCandidateLimit,String rerankingModelId,String rerankingRevision,String rerankingDownloadUrl,String rerankingCachePath,String rerankingModelPath,String rerankingBaseUrl,String rerankingRemoteModel,String rerankingApiKey,int rerankingMaxInputCharacters,int rerankingTimeoutSeconds,boolean answeringEnabled,String answeringBaseUrl,String answeringModel,String answeringApiKey){public ProviderForm(boolean embeddingsEnabled,String embeddingProvider,String embeddingModelId,String embeddingRevision,String embeddingDownloadUrl,String embeddingCachePath,String embeddingModelPath,String embeddingBaseUrl,String embeddingRemoteModel,String embeddingApiKey,int embeddingDimensions,int embeddingMaxInputCharacters,boolean rerankingEnabled,String rerankingProvider,int rerankingCandidateLimit,String rerankingModelId,String rerankingRevision,String rerankingDownloadUrl,String rerankingCachePath,String rerankingModelPath,String rerankingBaseUrl,String rerankingRemoteModel,String rerankingApiKey,int rerankingMaxInputCharacters,int rerankingTimeoutSeconds,boolean answeringEnabled,String answeringBaseUrl,String answeringModel,String answeringApiKey){this(embeddingsEnabled,embeddingProvider,embeddingModelId,embeddingRevision,embeddingDownloadUrl,embeddingCachePath,embeddingModelPath,embeddingBaseUrl,embeddingRemoteModel,embeddingApiKey,embeddingDimensions,embeddingMaxInputCharacters,true,rerankingEnabled,rerankingProvider,rerankingCandidateLimit,rerankingModelId,rerankingRevision,rerankingDownloadUrl,rerankingCachePath,rerankingModelPath,rerankingBaseUrl,rerankingRemoteModel,rerankingApiKey,rerankingMaxInputCharacters,rerankingTimeoutSeconds,answeringEnabled,answeringBaseUrl,answeringModel,answeringApiKey);}}
}
