spring:
  datasource:
    url: jdbc:h2:mem:contextcrate-test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: validate
contextcrate:
  artifacts:
    path: target/test-data/artifacts
  index:
    path: target/test-data/index
