package tech.wenisch.contextcrate.index;

import com.fasterxml.jackson.databind.*;
import java.io.IOException; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.util.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component;
import tech.wenisch.contextcrate.config.ContextCrateProperties; import tech.wenisch.contextcrate.domain.*; import tech.wenisch.contextcrate.embedding.EmbeddingProvider;
import tech.wenisch.contextcrate.repository.CrateRepository;

@Component @ConditionalOnProperty(name="contextcrate.index.backend",havingValue="opensearch")
public class OpenSearchSearchIndex implements SearchIndex {
  private final HttpClient client=HttpClient.newHttpClient(); private final ObjectMapper mapper; private final String endpoint,prefix; private final EmbeddingProvider embeddings; private final ContextCrateProperties.Retrieval retrieval;private final CrateRepository crates;
  public OpenSearchSearchIndex(ContextCrateProperties p,ObjectMapper mapper,EmbeddingProvider embeddings,CrateRepository crates){this.mapper=mapper;endpoint=p.index().endpoint().replaceAll("/+$","");prefix=p.index().prefix();this.embeddings=embeddings;this.crates=crates;retrieval=p.retrieval();}
  private int generation(UUID crateId){return crates.findById(crateId).orElseThrow().getActiveIndexGeneration();}
  private String index(UUID crateId){return index(crateId,generation(crateId));}
  private String index(UUID crateId,int generation){return prefix+"-crate-"+crateId+"-"+generation;}
  @Override public void initialize(UUID crateId)throws IOException,InterruptedException {initialize(crateId,generation(crateId));}
  private void initialize(UUID crateId,int generation)throws IOException,InterruptedException { var props=new LinkedHashMap<String,Object>(); for(String key:List.of("kind","parent_id","run_id","url","language","content_hash"))props.put(key,Map.of("type","keyword"));for(String key:List.of("url_text","title","heading","text"))props.put(key,Map.of("type","text"));props.put("ordinal",Map.of("type","integer")); if (embeddings.descriptor().dimensions() > 0) { props.put("embedding_model",Map.of("type","keyword"));props.put("embedding",Map.of("type","knn_vector","dimension",embeddings.descriptor().dimensions(),"method",Map.of("name","hnsw","engine","lucene","space_type","cosinesimil"))); } request("PUT","/"+index(crateId,generation),mapper.writeValueAsString(Map.of("settings",Map.of("index.knn",true),"mappings",Map.of("properties",props))),Set.of(200,400)); }
  @Override public void upsert(NormalizedDocument d,List<DocumentChunk> chunks)throws IOException,InterruptedException {upsertGeneration(d.getCrateId(),generation(d.getCrateId()),d,chunks);}
  @Override public void upsertGeneration(UUID crateId,int generation,NormalizedDocument d,List<DocumentChunk> chunks)throws IOException,InterruptedException {if(!crateId.equals(d.getCrateId())||chunks.stream().anyMatch(c->!crateId.equals(c.getCrateId())))throw new IllegalArgumentException("Index input crosses crate boundary");try(var ignored=tech.wenisch.contextcrate.config.CrateContext.use(crateId)){initialize(crateId,generation);try{StringBuilder bulk=new StringBuilder();append(bulk,crateId,generation,d.getId().toString(),source(d,"document",null,d.getBody(),embeddings.available()?embeddings.embedDocuments(List.of(d.getBody())).getFirst():null));for(var c:chunks)append(bulk,crateId,generation,c.getId().toString(),source(d,"chunk",c,c.getContent(),embeddings.available()?embeddings.embedDocuments(List.of(c.getContent())).getFirst():null));request("POST","/_bulk",bulk.toString(),Set.of(200));}catch(Exception e){throw new IOException("Could not create document embeddings",e);}}}
  private Map<String,Object> source(NormalizedDocument d,String kind,DocumentChunk c,String text,float[] vector){var s=new LinkedHashMap<String,Object>();s.put("kind",kind);s.put("parent_id",d.getId().toString());s.put("run_id",d.getRunId().toString());s.put("url",d.getSourceUri());s.put("url_text",d.getSourceUri());s.put("title",nullable(d.getTitle()));s.put("language",nullable(d.getLanguage()));s.put("text",text);s.put("content_hash",c==null?d.getContentHash():c.getContentHash());if(c!=null){s.put("heading",nullable(c.getHeading()));s.put("ordinal",c.getOrdinal());}if(vector!=null){s.put("embedding",vector);s.put("embedding_model",embeddings.descriptor().modelId()+":"+embeddings.descriptor().version());}return s;}
  private void append(StringBuilder b,UUID crateId,int generation,String id,Map<String,Object>s)throws IOException{b.append(mapper.writeValueAsString(Map.of("index",Map.of("_index",index(crateId,generation),"_id",id)))).append('\n').append(mapper.writeValueAsString(s)).append('\n');}
  @Override public void delete(UUID crateId,UUID id)throws IOException,InterruptedException{request("POST","/"+index(crateId)+"/_delete_by_query",mapper.writeValueAsString(Map.of("query",Map.of("term",Map.of("parent_id",id.toString())))),Set.of(200));}
  @Override public SearchResults search(SearchRequest r)throws IOException,InterruptedException{try(var ignored=tech.wenisch.contextcrate.config.CrateContext.use(r.crateId())){initialize(r.crateId());if(r.query().isBlank())return new SearchResults(r.query(),mode(r),List.of());String mode=mode(r);try{List<SearchHit>lex=mode.equals("semantic")?List.of():searchBody(r,false);List<SearchHit>sem=mode.equals("lexical")?List.of():searchBody(r,true);return new SearchResults(r.query(),mode,mode.equals("hybrid")?fuse(lex,sem,r.limit()):limit(mode.equals("lexical")?lex:sem,r.limit()));}catch(Exception e){if(e instanceof IOException io)throw io;throw new IOException("Search failed",e);}}}
  private String mode(SearchRequest r){return r.mode()!=null?r.mode():(embeddings.available()?retrieval.defaultMode():"lexical");}
  private List<SearchHit> searchBody(SearchRequest r,boolean semantic)throws Exception{if(semantic&&!embeddings.available())throw new IllegalStateException("Semantic search requested but embeddings are unavailable");List<Map<String,Object>> filters=filters(r);Map<String,Object> query;if(semantic){query=Map.of("knn",Map.of("embedding",Map.of("vector",embeddings.embedQuery(r.query()),"k",retrieval.candidateLimit(),"filter",filters.isEmpty()?Map.of("match_all",Map.of()):Map.of("bool",Map.of("filter",filters)))));}else {var bool=new LinkedHashMap<String,Object>();bool.put("must",List.of(Map.of("multi_match",Map.of("query",r.query(),"fields",List.of("title^3","heading^2","text","url_text")))));if(!filters.isEmpty())bool.put("filter",filters);query=Map.of("bool",bool);}var body=Map.of("size",retrieval.candidateLimit(),"query",query,"highlight",Map.of("fields",Map.of("text",Map.of(),"heading",Map.of())));JsonNode hits=mapper.readTree(request("POST","/"+index(r.crateId())+"/_search",mapper.writeValueAsString(body),Set.of(200))).path("hits").path("hits");List<SearchHit>out=new ArrayList<>();for(JsonNode h:hits)out.add(hit(h,r.query(),!semantic));return out;}
  private static List<Map<String,Object>> filters(SearchRequest r){var x=new ArrayList<Map<String,Object>>();if(r.kind()!=null)x.add(Map.of("term",Map.of("kind",r.kind())));if(r.runId()!=null)x.add(Map.of("term",Map.of("run_id",r.runId().toString())));return x;}
  @Override public void commit(UUID crateId)throws IOException,InterruptedException{commitGeneration(crateId,generation(crateId));}
  @Override public void commitGeneration(UUID crateId,int generation)throws IOException,InterruptedException{request("POST","/"+index(crateId,generation)+"/_refresh","",Set.of(200));}
  @Override public IndexHealth health(UUID crateId){try{long count=mapper.readTree(request("GET","/"+index(crateId)+"/_count",null,Set.of(200))).path("count").asLong();return new IndexHealth(crateId,"opensearch",true,count,endpoint+"; embeddings="+embeddings.available());}catch(Exception e){return new IndexHealth(crateId,"opensearch",false,0,e.getMessage());}}
  @Override public void deleteGeneration(UUID crateId,int generation)throws IOException,InterruptedException{request("DELETE","/"+index(crateId,generation),null,Set.of(200,404));}
  @Override public void deleteNamespace(UUID crateId)throws IOException,InterruptedException{request("DELETE","/"+prefix+"-crate-"+crateId+"-*",null,Set.of(200,404));}
  private String request(String method,String path,String body,Set<Integer>expected)throws IOException,InterruptedException{var b=HttpRequest.newBuilder(URI.create(endpoint+path)).header("Content-Type","application/json");var response=client.send(body==null?b.method(method,HttpRequest.BodyPublishers.noBody()).build():b.method(method,HttpRequest.BodyPublishers.ofString(body,StandardCharsets.UTF_8)).build(),HttpResponse.BodyHandlers.ofString());if(!expected.contains(response.statusCode()))throw new IOException("OpenSearch "+method+" "+path+" returned "+response.statusCode()+": "+response.body());return response.body();}
  private static SearchHit hit(JsonNode h,String q,boolean lexical){var s=h.path("_source");String kind=s.path("kind").asText();UUID doc=UUID.fromString(s.path("parent_id").asText());UUID id=UUID.fromString(kind.equals("chunk")?h.path("_id").asText():s.path("parent_id").asText());String text=s.path("text").asText("");String snippet=h.path("highlight").path("text").isArray()&&h.path("highlight").path("text").size()>0?h.path("highlight").path("text").get(0).asText():snippet(text,q);float score=(float)h.path("_score").asDouble();return new SearchHit(id,doc,UUID.fromString(s.path("run_id").asText()),kind,s.path("title").asText(null),s.path("url").asText(null),kind.equals("chunk")?s.path("ordinal").asInt():null,snippet,score,lexical?score:null,lexical?null:score);}
  private List<SearchHit> fuse(List<SearchHit>a,List<SearchHit>b,int n){var all=new LinkedHashMap<UUID,SearchHit>();var score=new HashMap<UUID,Float>();for(int i=0;i<a.size();i++){var h=a.get(i);all.put(h.id(),h);score.merge(h.id(),1f/(retrieval.rrfConstant()+i+1),Float::sum);}for(int i=0;i<b.size();i++){var h=b.get(i);all.putIfAbsent(h.id(),h);score.merge(h.id(),1f/(retrieval.rrfConstant()+i+1),Float::sum);}return all.values().stream().map(h->new SearchHit(h.id(),h.documentId(),h.runId(),h.kind(),h.title(),h.sourceUri(),h.chunkOrdinal(),h.snippet(),score.get(h.id()),find(a,h.id(),true),find(b,h.id(),false))).sorted(Comparator.comparing(SearchHit::score).reversed().thenComparing(h->h.id().toString())).limit(n).toList();}private static Float find(List<SearchHit>x,UUID id,boolean l){return x.stream().filter(h->h.id().equals(id)).map(h->l?h.lexicalScore():h.semanticScore()).findFirst().orElse(null);}private static List<SearchHit>limit(List<SearchHit>x,int n){return x.stream().limit(n).toList();}private static String nullable(String x){return x==null?"":x;}private static String snippet(String t,String q){if(t.length()<=240)return t;int p=t.toLowerCase(Locale.ROOT).indexOf(q.toLowerCase(Locale.ROOT));int a=p<0?0:Math.max(0,p-100),b=Math.min(t.length(),a+240);return(a>0?"...":"")+t.substring(a,b)+(b<t.length()?"...":"");}
}
