apiVersion: v1
kind: Service
metadata:
  name: {{ include "contextcrate.fullname" . }}
  labels: {{- include "contextcrate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ if eq .Values.profile "standalone" }}all{{ else }}control-plane{{ end }}
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: http }]
