{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harvex.fullname" . }}
  labels: {{- include "harvex.labels" . | nindent 4 }}
spec:
  accessModes: [{{ .Values.persistence.accessMode | quote }}]
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources: { requests: { storage: {{ .Values.persistence.size }} } }
{{- end }}
